apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-configuration
data:
  bridge.properties: |
    bridge.id=bridge-sidecar

    # HTTP related settings
    http.enabled=true
    http.host=127.0.0.1
    http.port=8080

    # Configuration Providers
    kafka.config.providers=env
    kafka.config.providers.env.class=io.strimzi.kafka.EnvVarConfigProvider

    # General Kafka settings
    kafka.bootstrap.servers=${env:BOOTSTRAP_SERVERS}
    kafka.security.protocol=SASL_SSL
    kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='...'   password='...';
    kafka.sasl.mechanism=PLAIN

    # Kafka Producer options
    kafka.producer.acks=1
    kafka.producer.security.protocol=SASL_SSL
    kafka.producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='...'   password='...';
    kafka.producer.sasl.mechanism=PLAIN

    # Kafka Consumer options
    kafka.consumer.auto.offset.reset=earliest
