apiVersion: v1
kind: Pod
metadata:
  name: bridge-sidecar
spec:
  containers:
    - name: main
      image: centos:7
      command: ["sh", "-c", "sleep 3600"]
    - name: bridge
      image: quay.io/strimzi/kafka-bridge:0.20.2
      command: ["/opt/strimzi/bin/kafka_bridge_run.sh", "--config-file", "/etc/strimzi-bridge/bridge.properties"]
      env:
        - name: BOOTSTRAP_SERVERS
          value: ....us-central1.gcp.confluent.cloud:9092
      volumeMounts:
        - name: bridge-configuration
          mountPath: /etc/strimzi-bridge
  volumes:
    - name: bridge-configuration
      configMap:
        name: bridge-configuration
  restartPolicy: Never
