apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 3
  bootstrapServers: ....us-central1.gcp.confluent.cloud:9092
  authentication:
    type: plain
    username: ...
    passwordSecret:
      secretName: bridge-secret
      password: my-password.txt
  producer:
    config:
      acks: 1
      delivery.timeout.ms: 300000
  http:
    port: 8080
